# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:30
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='T\xedtulo')),
                ('sub_title', models.CharField(max_length=300, null=True, verbose_name='Sub-t\xedtulo')),
                ('intro', models.TextField(verbose_name='Introdu\xe7\xe3o')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Corpo do texto')),
                ('date', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(blank=True, max_length=500, verbose_name='Autor')),
                ('miniature', models.ImageField(max_length=255, upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura')),
                ('tag', models.CharField(max_length=300, verbose_name='Tag para filtro')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Fullwidth_slider_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phrase', models.CharField(max_length=50, verbose_name='Primeira frase (menor)')),
                ('second_phrase', models.CharField(max_length=50, verbose_name='Segunda frase (em destaque)')),
                ('slide_image', models.ImageField(upload_to='slide_item/%Y/%m/%d/', verbose_name='Imagem do slide')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='T\xedtulo')),
                ('sub_title', models.CharField(max_length=300, verbose_name='Subt\xedtulo')),
                ('study', models.TextField(blank=True, verbose_name='Estudo do caso')),
                ('results', models.TextField(blank=True, verbose_name='Resultado')),
                ('experience', models.TextField(blank=True, verbose_name='Experi\xeancia')),
                ('client', models.CharField(max_length=300, verbose_name='Cliente')),
                ('date', models.DateField(auto_now=True)),
                ('online', models.CharField(blank=True, max_length=500, verbose_name='URL do cliente')),
                ('miniature', models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura')),
                ('tag', models.CharField(max_length=300, verbose_name='Tag para filtro')),
                ('lat', models.CharField(blank=True, max_length=100, verbose_name='Latitude')),
                ('lon', models.CharField(blank=True, max_length=100, verbose_name='Longitude')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Portfolio/case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='ServiceIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to=core.models.generate_filename, verbose_name='\xcdcone')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='T\xedtulo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(max_length=300, verbose_name='\xc2ncora/Tab')),
                ('icon', models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone')),
                ('title', models.CharField(max_length=300, verbose_name='T\xedtulo')),
                ('mention', models.TextField(blank=True, verbose_name='Cita\xe7\xe3o')),
                ('author', models.CharField(max_length=300, verbose_name='Autor')),
                ('abstract', models.TextField(blank=True, verbose_name='Conceito')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclus\xe3o')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descri\xe7\xe3o')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Service/case',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=core.models.generate_filename, verbose_name='Imagem')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='T\xedtulo')),
                ('desc', models.TextField(blank=True, max_length=1500, verbose_name='Descri\xe7\xe3o')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='core.ServiceItem')),
            ],
        ),
        migrations.AddField(
            model_name='serviceicons',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icones', to='core.ServiceItem'),
        ),
        migrations.AddField(
            model_name='portfolioimages',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.PortfolioItem'),
        ),
        migrations.AddField(
            model_name='blogimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.BlogPost'),
        ),
    ]
