# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 18:50
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fullwidth_slider_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_prhase', models.CharField(max_length=50, verbose_name='Primeira frase (menor)')),
                ('second_prhase', models.CharField(max_length=50, verbose_name='Segunda frase (em destaque)')),
                ('slide_image', models.ImageField(upload_to='slide_item/%Y/%m/%d/', verbose_name='Imagem do slide')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='T\xedtulo')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Subt\xedtulo')),
                ('first_image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)')),
                ('second_image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Segunda imagem(slide)')),
                ('third_image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Terceira imagem(slide)')),
                ('study', models.TextField(verbose_name='Estudo do caso')),
                ('results', models.TextField(blank=True, verbose_name='Resultado')),
                ('experience', models.TextField(blank=True, verbose_name='Experi\xeancia')),
                ('client', models.CharField(max_length=200, verbose_name='Cliente')),
                ('date', models.DateField(auto_now=True)),
                ('online', models.CharField(blank=True, max_length=500, verbose_name='URL do cliente')),
                ('miniature', models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag para filtro')),
            ],
            options={
                'verbose_name': 'Portfolio/case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
