# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullwidth_slider_item',
            old_name='first_prhase',
            new_name='first_phrase',
        ),
        migrations.RenameField(
            model_name='fullwidth_slider_item',
            old_name='second_prhase',
            new_name='second_phrase',
        ),
    ]
