# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 20:46
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170302_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='T\xedtulo')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Subt\xedtulo')),
                ('study', models.TextField(blank=True, verbose_name='Estudo do caso')),
                ('results', models.TextField(blank=True, verbose_name='Resultado')),
                ('experience', models.TextField(blank=True, verbose_name='Experi\xeancia')),
                ('client', models.CharField(max_length=200, verbose_name='Cliente')),
                ('date', models.DateField(auto_now=True)),
                ('online', models.CharField(blank=True, max_length=500, verbose_name='URL do cliente')),
                ('miniature', models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag para filtro')),
                ('lat', models.CharField(blank=True, max_length=100, verbose_name='Latitude')),
                ('lon', models.CharField(blank=True, max_length=100, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Portfolio/case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.DeleteModel(
            name='Portfolio_item',
        ),
        migrations.AddField(
            model_name='portfolioimages',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.PortfolioItem'),
        ),
    ]
