# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 16:53
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170302_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='T\xedtulo')),
                ('intro', models.TextField(verbose_name='Introdu\xe7\xe3o')),
                ('content', models.TextField(verbose_name='Corpo do texto')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=500, verbose_name='Autor')),
                ('miniature', models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag para filtro')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='blogimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.BlogPost'),
        ),
    ]
