# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 14:42
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170303_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone')),
                ('title', models.CharField(max_length=20, verbose_name='T\xedtulo')),
                ('mention', models.TextField(blank=True, verbose_name='Cita\xe7\xe3o')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('abstract', models.TextField(blank=True, verbose_name='Conceito')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclus\xe3o')),
                ('description', models.TextField(blank=True, verbose_name='Descri\xe7\xe3o')),
                ('icon_disc', models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone Discuss\xe3o')),
                ('icon_plan', models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone Planejamento')),
                ('icon_acti', models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone A\xe7\xe3o')),
                ('method_img', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem da Metodologia')),
                ('method_title', models.CharField(max_length=20, verbose_name='T\xedtulo da Metodologia')),
                ('method_desc', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o da Metdologia')),
                ('sustainable_img', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem de Sustentabilidade')),
                ('sustainable_method_title', models.CharField(max_length=20, verbose_name='T\xedtulo da Sustentabilidade')),
                ('sustainable_method_desc', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o da Sustentabilidade')),
                ('dev_img', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem de Desenvolvimento')),
                ('dev_method_title', models.CharField(max_length=20, verbose_name='T\xedtulo da Desenvolvimento')),
                ('dev_method_desc', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o da Desenvolvimento')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Service/case',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-date'], 'verbose_name': 'Portfolio/case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Corpo do texto'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
    ]
