# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:43
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170307_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)')),
            ],
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='action_icon',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone A\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='dev_img',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem de Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='disc_icon',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone Discuss\xe3o'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='icon',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='method_img',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem da Metodologia'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='plan_icon',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='\xcdcone Planejamento'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='sustainable_img',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem de Sustentabilidade'),
        ),
        migrations.AddField(
            model_name='serviceimages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.ServiceItem'),
        ),
    ]
