# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170307_1437'),
        ('core', '0015_auto_20170308_0927'),
    ]

    operations = [
    ]
