# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 17:29
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20170310_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='anchor',
            field=models.CharField(default=True, max_length=200, verbose_name='\xc2ncora/Tab'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
    ]
