# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:23
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170313_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='dev_img',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='dev_method_desc',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='dev_method_title',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='method_desc',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='method_img',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='method_title',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='sustainable_img',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='sustainable_method_desc',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='sustainable_method_title',
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='servicemethod',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='core.ServiceItem'),
        ),
    ]
