# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:31
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170313_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sub_title',
            field=models.CharField(max_length=300, null=True, verbose_name='Sub-t\xedtulo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=300, verbose_name='Tag para filtro'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=300, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(max_length=300, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='sub_title',
            field=models.CharField(max_length=300, verbose_name='Subt\xedtulo'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='tag',
            field=models.CharField(max_length=300, verbose_name='Tag para filtro'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=300, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='serviceicons',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='anchor',
            field=models.CharField(max_length=300, verbose_name='\xc2ncora/Tab'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='author',
            field=models.CharField(max_length=300, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='title',
            field=models.CharField(max_length=300, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='servicemethod',
            name='desc',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='servicemethod',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servicemethod',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='T\xedtulo'),
        ),
    ]
