# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170313_1707'),
        ('core', '0018_auto_20170310_1431'),
    ]

    operations = [
    ]
