# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 16:11
from __future__ import unicode_literals

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20170324_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_filename, verbose_name='Primeira imagem(slide)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='miniature',
            field=models.ImageField(upload_to=core.models.generate_filename_miniature, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='anchor',
            field=models.CharField(max_length=300, verbose_name='\xc2ncora/Tab'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
