# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170714_1415'),
        ('core', '0030_auto_20170714_1419'),
    ]

    operations = [
    ]
